import Provider from "@/components/Provider";
import StyleLayout from "@/components/StyleLayout";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body>
        <Provider>
          <StyleLayout>{children}</StyleLayout>
        </Provider>
      </body>
    </html>
  );
}
